# Generated by Django 4.0.5 on 2022-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_options_alter_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(default='prod.jpg', upload_to='product')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
