# Generated by Django 4.0.5 on 2022-06-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_available_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='min',
            field=models.IntegerField(default=1),
        ),
    ]
