# Generated by Django 3.2.4 on 2022-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='avatar.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
