# Generated by Django 3.2.4 on 2022-06-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
    ]
