# Generated by Django 4.0.5 on 2022-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_alter_shopcart_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='size',
            field=models.CharField(blank=True, default='a', max_length=70, null=True),
        ),
    ]
