# Generated by Django 4.0.5 on 2022-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0005_alter_shopcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='subtotal',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
