# Generated by Django 4.0.5 on 2022-06-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0006_shopcart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
