# Generated by Django 4.0.5 on 2022-06-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0008_shopcart_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
