# Generated by Django 4.0.5 on 2022-06-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0009_alter_shopcart_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='size',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
